Import('env', 'BUILD_IN_TMP', 'LINUX', 'GLIB', 'GTK', 'LUA', 'CAIRO', 'GTHREAD', 'libtetris', 'RSVG')

gtk_env = env.Clone()

sources = ['main.c', 'connect.c', 'network.c', 'chat.c', 'context.c',
           'drawing_area.c', 'mainwindow.c', 'plugins.c']

if BUILD_IN_TMP:
    gtk_env.VariantDir('/tmp/tetristar/gtk', '.', duplicate=0)
    sources = map(lambda x: '/tmp/tetristar/gtk/' + x, sources)

if LINUX == '1':
    gtk_env['LIBS'] += ['enet']
else:
    sources += ['/usr/local/lib/libenet.a']

LIBS = [LUA, GLIB, GTK, CAIRO, GTHREAD, RSVG]

for lib in LIBS:
    gtk_env.ParseConfig('pkg-config ' + lib + ' --cflags --libs')

gtk_env['LIBS'] += ['pthread', libtetris]

client = gtk_env.Program(target = 'client', source = sources)

