Import('env', 'LINUX', 'GLIB', 'GTK', 'LUA', 'libtetris')

gtk_env = env.Clone()

sources = ['main.c', 'connect.c', 'network.c', 'chat.c']

if LINUX == '1':
    gtk_env['LIBS'] += ['enet']
else:
    sources += ['/usr/local/lib/libenet.a']

LIBS = [LUA, GLIB, GTK]

for lib in LIBS:
    gtk_env.ParseConfig('pkg-config ' + lib + ' --cflags --libs')

gtk_env['LIBS'] += ['pthread', libtetris]

client = gtk_env.Program(target = 'client', source = sources)

