Import('env', 'LUA', 'GLIB')

lib_env = env.Clone()

sources = ['libtetris.c', 'state.c', 'player.c', 'lua_functions.c', 'util.c']
LIBS = [LUA, GLIB]

for lib in LIBS:
    lib_env.ParseConfig('pkg-config ' + lib + ' --cflags --libs')

libtetris = lib_env.SharedLibrary(target = 'tetris', source = sources)
Return('libtetris')
