Import('env', 'BUILD_IN_TMP', 'libtetris', 'LUA', 'GLIB', 'GTHREAD', 'CHECK')

test_env = env.Clone()

sources = ['libtetris.c']
if BUILD_IN_TMP:
    test_env.VariantDir('/tmp/tetristar/tests', '.', duplicate=0)
    sources = map(lambda x: '/tmp/tetristar/tests/' + x, sources)

LIBS = [LUA, GLIB, GTHREAD, CHECK]

for lib in LIBS:
    test_env.ParseConfig('pkg-config ' + lib + ' --cflags --libs')

test_env['LIBS'] += [libtetris]

program = test_env.Program(target = 'libtetris', source = sources)
# TODO: run the test from scons
