Import('env', 'LINUX')

simple_env = env.Clone()

sources = ['simple.c']

if LINUX == '1':
    simple_env['LIBS'] += ['enet']
else:
    sources += ['/usr/local/lib/libenet.a']

client = simple_env.Program(target = 'simple', source = sources)
