Import('env', 'CFLAGS')

sources = ['main.c', 'configuration.c']
LIBS = ['lua-5.1']

for lib in LIBS:
    env.ParseConfig('pkg-config ' + lib + ' --cflags --libs')

server = env.Program(target = 'server', source = sources,
                     # lua seems to need -lm but its .pc file doesn't say so
                     CFLAGS = CFLAGS, LIBS = LIBS + ['m'], 
                     LIBPATH = ['/usr/lib', '/usr/local/lib'])
