Import('env', 'LINUX', 'LUA', 'GLIB', 'libtetris')

server_env = env.Clone()

sources = ['main.c', 'configuration.c', 'network.c', 'plugins.c']

if LINUX == '1':
    server_env['LIBS'] += ['enet']
else:
    sources += ['/usr/local/lib/libenet.a']

LIBS = [LUA, GLIB]

for lib in LIBS:
    server_env.ParseConfig('pkg-config ' + lib + ' --cflags --libs')

server_env['LIBS'] += [libtetris]

server = server_env.Program(target = 'server', source = sources)
